openapi: 3.0.1
info:
  title: Sample API
  version: "1.0"

paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
